vim.cmd("source ~/.config/nvim/lua/plugins/init.vim")
require("core.keymaps")
require("core.options")
-- require("core.sessions")
require("plugins.treesitter")
require("plugins.colorscheme")
require("plugins.comments")
require("plugins.maximize")
require("plugins.lua-line")
require("plugins.telescope_conf")
require("plugins.icons")
require("plugins.file_explorer_conf")
require("plugins.bufferline")
require("plugins.completition.completition")
require("plugins.lsp.lsp_conf")
require("plugins.neogen")
require("plugins.debugger.debugger")
require("plugins.debugger.debugger_ui")
require("plugins.git_conf")
require("plugins.autopairs")
require("plugins.mason.mason")
require("plugins.startup")
require("plugins.colorizer")
